### ISSUE TITLE
FlexboxLayoutManager

### ISSUE THREAD

**Issue by mflk007** [google/flexbox-layout#276]
Stack trace:  
java.lang.ArrayIndexOutOfBoundsException: length=19; index=-1
at com.google.android.flexbox.FlexboxLayoutManager.updateLayoutState(FlexboxLayoutManager.java:1678)
at com.google.android.flexbox.FlexboxLayoutManager.handleScrolling(FlexboxLayoutManager.java:1656)
at com.google.android.flexbox.FlexboxLayoutManager.scrollVerticallyBy(FlexboxLayoutManager.java:1634)
at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1504)
at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2461)
at android.view.View.dispatchTouchEvent(View.java:10008)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2665)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2344)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
at com.wifi.key.user.view.SlidingLayout.dispatchTouchEvent(SlidingLayout.java:307)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:447)
at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
at android.app.Activity.dispatchTouchEvent(Activity.java:3213)
at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:409)
at android.view.View.dispatchPointerEvent(View.java:10228)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4845)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4705)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4238)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4291)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4257)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4384)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4265)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4441)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4238)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4291)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4257)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4265)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4238)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6665)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6639)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6600)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6792)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:181)
at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6739)
at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6820)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:923)
at android.view.Choreographer.doCallbacks(Choreographer.java:735)
at android.view.Choreographer.doFrame(Choreographer.java:661)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:909)
at android.os.Handler.handleCallback(Handler.java:755)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:156)
at android.app.ActivityThread.main(ActivityThread.java:6524)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by thagikura** [comment]
Thanks for reporting this.
Could you provide more details such as a sample project or code that can reproduce this?

**Comment by mflk007** [comment]
When the slide occurs, the list automatically slides, and then slides on the crash.  Why is there an automatic slide？

**Comment by mflk007** [comment]
multiItem type, Using 5 kinds

**Comment by mflk007** [comment]
in tab fragment

**Comment by mflk007** [comment]
@thagikura must to be use com.android.support > 25  , i use  23.2.0 ....

**Comment by thagikura** [comment]
Please share the sample project that can reproduce the issue, I'm afraid I don't understand the issue .

**Comment by thagikura** [comment]
I can't reproduce this. Please reopen if this isn't still fixed.
