### ISSUE TITLE
how to exculd v4?I did not include this 

### ISSUE THREAD

**Issue by shiyuexun** [google/flexbox-layout#279]
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/v4/widget/SwipeRefreshLayout$2.class

**Comment by shiyuexun** [comment]
java.lang.ClassCastException: android.support.v7.widget.RecyclerView$LayoutParams cannot be cast to com.google.android.flexbox.FlexItem
                                                                     at com.google.android.flexbox.FlexboxHelper.calculateFlexLines(FlexboxHelper.java:422)
                                                                     at com.google.android.flexbox.FlexboxHelper.calculateHorizontalFlexLines(FlexboxHelper.java:239)
                                                                     at com.google.android.flexbox.FlexboxLayoutManager.updateFlexLines(FlexboxLayoutManager.java:780)
                                                                     at com.google.android.flexbox.FlexboxLayoutManager.onLayoutChildren(FlexboxLayoutManager.java:606)
                                                                     at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                     at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3025)
                                                                     at android.view.View.measure(View.java:17879)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5629)
                                                                     at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:714)
                                                                     at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:90)
                                                                     at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1391)
                                                                     at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:784)
                                                                     at android.view.View.measure(View.java:17879)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5629)
                                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:459)
                                                                     at android.view.View.measure(View.java:17879)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5629)
                                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
                                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
                                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
                                                                     at android.view.View.measure(View.java:17879)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5629)
                                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:459)
                                                                     at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2670)
                                                                     at android.view.View.measure(View.java:17879)
                                                                     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2458)
                                                                     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1406)
                                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1644)
                                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1284)
                                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6625)
                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:603)
                                                                     at android.view.Choreographer.doFrame(Choreographer.java:572)
                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
                                                                     at android.os.Handler.handleCallback(Handler.java:815)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                     at android.os.Looper.loop(Looper.java:194)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5588)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:969)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)

**Comment by thagikura** [comment]
Sorry what operation did you try to do?

**Comment by shiyuexun** [comment]
i add headview.。。
this layout can addView?I tried, but not show

**Comment by thagikura** [comment]
Sorry the issue wasn't clear, could you reopen it with your sample project?
