### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1  

### ISSUE THREAD

**Issue by Neha1490** [google/flexbox-layout#325]
I am getting this error while scrolling on item swapping -  

Stack trace -

Process: com.thoughts2binary.xelpmoc, PID: 30831
                                                                             java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
                                                                                 at com.google.android.flexbox.FlexboxHelper.clearFlexLines(FlexboxHelper.java:1922)
                                                                                 at com.google.android.flexbox.FlexboxLayoutManager.updateLayoutState(FlexboxLayoutManager.java:1873)
                                                                                 at com.google.android.flexbox.FlexboxLayoutManager.handleScrolling(FlexboxLayoutManager.java:1752)
                                                                                 at com.google.android.flexbox.FlexboxLayoutManager.scrollVerticallyBy(FlexboxLayoutManager.java:1730)
                                                                                 at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1727)
                                                                                 at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2927)
                                                                                 at android.view.View.dispatchTouchEvent(View.java:9943)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2663)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2344)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                                 at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:411)
                                                                                 at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1810)
                                                                                 at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
                                                                                 at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
                                                                                 at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:373)
                                                                                 at android.view.View.dispatchPointerEvent(View.java:10163)
                                                                                 at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4434)
                                                                                 at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4302)
                                                                                 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
                                                                                 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3902)
                                                                                 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3868)
                                                                                 at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3995)
                                                                                 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3876)
                                                                                 at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4052)
                                                                                 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
                                                                                 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3902)
                                                                                 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3868)
                                                                                 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3876)
                                                                                 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
                                                                                 at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6210)
                                                                                 at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6184)
                                                                                 at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6145)
                                                                                 at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6313)
                                                                                 at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                                 at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                                 at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                                                 at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6284)
                                                                                 at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6336)
06-29 17:40:07.441 30831-30831/com.thoughts2binary.xelpmoc E/AndroidRuntime:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
                                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                                                                                 at android.view.Choreographer.doFrame(Choreographer.java:613)
                                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                                                                                 at android.os.Handler.handleCallback(Handler.java:751)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

I have already gone through issues #276 and #222
## What I am trying to do is-
a) Replacing item in recycler view with some other item.
b) After replacement calling  adapter.notifyItemChanged(0);

## Version of the flexbox library
0.3.0-alpha4

**Comment by MGaetan89** [comment]
Have you tried with the recently released v0.3.0?

**Comment by Neha1490** [comment]
Yes I am using the same version. I have already mentioned it in my question.

**Comment by MGaetan89** [comment]
In your original question, you are talking about 0.3.0-alpha4.
A new version, 0.3.0 (no longer alpha), was released this week. That's why I ask.

**Comment by Neha1490** [comment]
Oh sorry for miscommunication,I am using above mentioned version only.

I will try with this version.

**Comment by thagikura** [comment]
Hi @Neha1490 

Thanks for the report. If you still see the error with the 0.3.0 version it's appreciated if you can link to your code or code snippet.

**Comment by Neha1490** [comment]
Hi

I have tried with above mentioned version i.e. 0.3.0 and its working fine now.

**Comment by IstiN** [comment]
Hi I have the same issue with 0.3.0
