### ISSUE TITLE
Crash on data-set update when DiffUtils is used

### ISSUE THREAD

**Issue by saket** [google/flexbox-layout#332]
- [x] I have searched [existing issues](https://github.com/google/flexbox-layout/issues) and confirmed this is not a duplicate

## Issues and steps to reproduce
I'm seeing this crash when trying to filter my list items using a search query:

```java
FATAL EXCEPTION: main
java.lang.ArrayIndexOutOfBoundsException: length=45; index=-1
    at com.google.android.flexbox.FlexboxLayoutManager$AnchorInfo.assignFromView(FlexboxLayoutManager.java:2863)
    at com.google.android.flexbox.FlexboxLayoutManager$AnchorInfo.access$1900(FlexboxLayoutManager.java:2792)
    at com.google.android.flexbox.FlexboxLayoutManager.updateAnchorFromChildren(FlexboxLayoutManager.java:1136)
    at com.google.android.flexbox.FlexboxLayoutManager.updateAnchorInfoForLayout(FlexboxLayoutManager.java:1032)
    at com.google.android.flexbox.FlexboxLayoutManager.onLayoutChildren(FlexboxLayoutManager.java:700)
    at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
    at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
    at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
```

**Steps to reproduce**
This started to happen after I added DiffUtils for showing item animations. Here's what I'm doing:

```java
List<FolderSubscription> oldSubscriptions = ...;
List<FolderSubscription> newSubscriptions = ...;

FolderSubscriptionDiffCallbacks callback = new FolderSubscriptionDiffCallbacks(oldSubscriptions, newSubscriptions);
DiffUtil.DiffResult folderDiffResult = DiffUtil.calculateDiff(callback, true /* detectMoves */);

folderAdapter.updateData(newSubscriptions);
folderDiffResult.dispatchUpdatesTo(folderAdapter);
```

## Version of the flexbox library
I tested on both v0.3-alpha3 and v0.3.

**Comment by thagikura** [comment]
Thanks for the report. I'm not familiar with RxJava, it is possible replace the chain without RxJava?

**Comment by Saketme** [comment]
Sorry for the late response. I have removed RxJava from my post.

**Comment by thagikura** [comment]
Sorry for the late response.
This looks to be an issue with FlexboxLayoutManager.
Marking as a bug.

**Comment by Saketme** [comment]
No problem, thanks @thagikura!

**Comment by shrpereira** [comment]
I'm having the same issue using Renderers library and their diff algorithm with FlexboxLayoutManager.

**Comment by shrpereira** [comment]
I'm having the same issue using Renderers library and their diff algorithm with FlexboxLayoutManager.
The lib algorithm is the following:

      DiffCallback diffCallback = new DiffCallback(collection, newList);
      DiffUtil.DiffResult diffResult = DiffUtil.calculateDiff(diffCallback);
      clear();
      addAll(newList);
      diffResult.dispatchUpdatesTo(this);

Changing from their `adapter.diffUpdate(list)` to the conventional updating the list and calling `adapter.notifyDataSetChanged();` works but I've lost the animation.

**Comment by derekcsm** [comment]
Would love to see DiffUtil support for animations as well

**Comment by Bringoff** [comment]
Any progress on this issue? I rely heavily on DiffUtils for proper animations

**Comment by Bringoff** [comment]
Method `updateAnchorFromChildren` in `FlexboxLayoutManager` contains such comment: 
```
            // If all visible views are removed in 1 pass, reference child might be out of bounds.
            // If that is the case, offset it back to 0 so that we use these pre-layout children.
```
but `out of bounds` crash throws from the line before this comment: `anchorInfo.assignFromView(referenceChild);`
I suppose this might be the issue.

**Comment by Bringoff** [comment]
I've made a temp fix for myself in my fork by adding a check if the position is equal to NO_POSITION in the method assignFromView. The changed lines can be found [here](https://github.com/HiTask/flexbox-layout/blob/ecc40a9dc3bc1ecbea5037665ca184a0e363983f/flexbox/src/main/java/com/google/android/flexbox/FlexboxLayoutManager.java#L2879). I'm not sure about solution correctness, but it didn't break tests and crash gone for me.

**Comment by thagikura** [comment]
@Bringoff thanks for you suggestion. Let me take a look at it.

**Comment by thagikura** [comment]
I'm trying to reproduce the crash again on this [branch](https://github.com/google/flexbox-layout/compare/fix_diffutil?expand=1), but no luck so far.
@Bringoff or is anyone able to share the code that can reproduce the quick?

The code looks good, but wanted to make sure if the fix is really appropriate.

**Comment by j-garin** [comment]
@thagikura still getting this FC

## Issues and steps to reproduce
Update the items in androidx.recyclerview.widget.RecyclerView with androidx.recyclerview.widget.ListAdapter

## Expected behavior
The list should handle multiple changes

## Version of the flexbox library
1.1.0

## Link to code
```
		val layoutManager = FlexboxLayoutManager(recyclerView.context)
				.apply {
					flexWrap = FlexWrap.WRAP
					flexDirection = FlexDirection.ROW
					justifyContent = JustifyContent.CENTER
					alignItems = AlignItems.CENTER
				}
		recyclerView.layoutManager = layoutManager
		recyclerView.adapter = adapter
```

happens when `adapter.submitList(newList)` gets called often. I have about 10 items in the list in my case, 1 item gets changed per call.

```
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:4941)
        at android.view.ViewGroup.addView(ViewGroup.java:4772)
        at android.view.ViewGroup.addView(ViewGroup.java:4712)
        at androidx.recyclerview.widget.RecyclerView$5.addView(RecyclerView.java:851)
        at androidx.recyclerview.widget.ChildHelper.addView(ChildHelper.java:107)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8336)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8294)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8282)
        at com.google.android.flexbox.FlexboxLayoutManager.layoutFlexLineMainAxisHorizontal(FlexboxLayoutManager.java:1513)
        at com.google.android.flexbox.FlexboxLayoutManager.layoutFlexLine(FlexboxLayoutManager.java:1434)
        at com.google.android.flexbox.FlexboxLayoutManager.fill(FlexboxLayoutManager.java:1286)
        at com.google.android.flexbox.FlexboxLayoutManager.onLayoutChildren(FlexboxLayoutManager.java:754)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
```
