### ISSUE TITLE
ArrayIndexOutOfBoundsException in updateLayoutState()

### ISSUE THREAD

**Issue by amasciul** [google/flexbox-layout#363]
Hi, I have a crash from time to time when updating data. It looks like `updateLayoutState()` throws an `IndexOutOfBoundsException` here:

`FlexboxLayoutManager` line 2057
```java
int firstVisiblePosition = getPosition(firstVisible);
int firstVisibleLinePosition = mFlexboxHelper.mIndexToFlexLine[firstVisiblePosition];
```
`getPosition(firstVisible)` seems to return -1 (NO_POSITION) sometimes. Maybe this is related to the activity being hidden behind another. It happens at least on versions 0.3.0 and 0.3.1

Here is the full stacktrace:
```
java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
    at com.google.android.flexbox.FlexboxLayoutManager.updateLayoutState(FlexboxLayoutManager.java:2058)
    at com.google.android.flexbox.FlexboxLayoutManager.handleScrollingCrossAxis(FlexboxLayoutManager.java:1930)
    at com.google.android.flexbox.FlexboxLayoutManager.fixLayoutEndGap(FlexboxLayoutManager.java:825)
    at com.google.android.flexbox.FlexboxLayoutManager.onLayoutChildren(FlexboxLayoutManager.java:762)
    at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3693)
    at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3109)
    at android.view.View.measure(View.java:19857)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
    at android.support.v7.widget.CardView.onMeasure(CardView.java:218)
    at android.view.View.measure(View.java:19857)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
    at android.view.View.measure(View.java:19857)
    at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1293)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
    at android.widget.ScrollView.onMeasure(ScrollView.java:340)
    at android.view.View.measure(View.java:19857)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
    at android.view.View.measure(View.java:19857)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
    at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
    at android.view.View.measure(View.java:19857)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
    at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:400)
    at android.view.View.measure(View.java:19857)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
    at android.view.View.measure(View.java:19857)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
    at android.view.View.measure(View.java:19857)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
    at com.android.internal.policy.DecorView.onMeasure(DecorView.java:689)
    at android.view.View.measure(View.java:19857)
    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2275)
    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1366)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1675)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
    at android.view.Choreographer.doCallbacks(Choreographer.java:686)
    at android.view.Choreographer.doFrame(Choreographer.java:621)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6119)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
```

**Comment by thagikura** [comment]
Thanks for filing this.

I really appreciate if you can share the code snippet or an example project that can reproduce the issue. Is it possible?

**Comment by NebirosFeR** [comment]
I have the same issue with same stack trace in my project. But I couldn't find stable way to reproduce it.

I use notifyDataSetChanged() and the crash happens rarely after data change. I have a RecyclerView with FlexboxLayoutManager inside AppBarLayout with CoordinatorLayout.

**Comment by fantasyRqg** [comment]
`

1 com.google.android.flexbox.FlexboxLayoutManager.c(Unknown Source)
--
2 com.google.android.flexbox.FlexboxLayoutManager.a(Unknown Source)
3 com.google.android.flexbox.FlexboxLayoutManager.a(Unknown Source)
4 com.google.android.flexbox.FlexboxLayoutManager.a(Unknown Source)
5 com.google.android.flexbox.FlexboxLayoutManager.b(Unknown Source)
6 com.google.android.flexbox.FlexboxLayoutManager.onLayoutChildren(Unknown Source)
7 android.support.v7.widget.RecyclerView.dispatchLayoutStep2(Unknown Source)
8 android.support.v7.widget.RecyclerView.onMeasure(Unknown Source)
9 android.view.View.measure(View.java:18813)
10 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5956)
11 android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
12 android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
13 android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
14 android.view.View.measure(View.java:18813)
15 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5956)
16 android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
17 android.view.View.measure(View.java:18813)
18 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5956)
19 android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
20 android.view.View.measure(View.java:18813)
21 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5956)
22 android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
23 android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
24 android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
25 android.view.View.measure(View.java:18813)
26 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5956)
27 android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
28 android.view.View.measure(View.java:18813)
29 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5956)
30 android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
31 android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
32 android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
33 android.view.View.measure(View.java:18813)
34 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5956)
35 android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
36 android.view.View.measure(View.java:18813)
37 android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1092)
38 android.widget.LinearLayout.onMeasure(LinearLayout.java:632)
39 android.view.View.measure(View.java:18813)
40 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5956)
41 android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
42 android.view.View.measure(View.java:18813)
43 android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:716)
44 android.widget.RelativeLayout.onMeasure(RelativeLayout.java:462)
45 android.view.View.measure(View.java:18813)
46 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5956)
47 android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
48 android.support.v7.widget.ContentFrameLayout.onMeasure(Unknown Source)
49 android.view.View.measure(View.java:18813)
50 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5956)
51 android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
52 android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
53 android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
54 android.view.View.measure(View.java:18813)
55 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5956)
56 android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
57 android.view.View.measure(View.java:18813)
58 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5956)
59 android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
60 android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
61 android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
62 android.view.View.measure(View.java:18813)
63 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5956)
64 android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
65 com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
66 android.view.View.measure(View.java:18813)
67 android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
68 android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
69 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
70 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
71 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
72 android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
73 android.view.Choreographer.doCallbacks(Choreographer.java:670)
74 android.view.Choreographer.doFrame(Choreographer.java:606)
75 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
76 android.os.Handler.handleCallback(Handler.java:739)
77 android.os.Handler.dispatchMessage(Handler.java:95)
78 android.os.Looper.loop(Looper.java:148)
79 android.app.ActivityThread.main(ActivityThread.java:5417)
80 java.lang.reflect.Method.invoke(Native Method)
81 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
82 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

`

**Comment by fantasyRqg** [comment]
seems same problem ```java.lang.ArrayIndexOutOfBoundsExceptionlength=10; index=-1
com.google.android.flexbox.FlexboxLayoutManager.void setFlexDirection(int)(Unknown Source)```

**Comment by sparklellama** [comment]
I'm having the same crash in  Line 1368:  int currentLineIndex = mFlexboxHelper.mIndexToFlexLine[getPosition(lastView)];

This also happens when a layout occurs while the fragment is obscured by other fragments

The code looks like it could use a little null safety... getPosition appears to return -1 a lot and it's used without checks all through this class

**Comment by fantasyRqg** [comment]
FlexboxLayoutManager use cachedViews which ViewHolder has been reseted. This my caused by RecyclerView is not visible

this is my workaround.

```java
        mListView.setItemViewCacheSize(10);
        adapter.setHasStableIds(true);
```

**Comment by sparklellama** [comment]
The FlexBoxLayoutManager doesn't seem to work well if your RecyclerViewAdapter doesn't call setStableIds(true).  This means it also has to implement GetItemId(int position), and return something meaningful ( an actual unique ID).  

If you do this, performance will be heaps better, animations will start working, and the thing will stop crashing all the time.

Potentially, as a fix, this library should enforce the use of stable IDs somehow?

**Comment by Evgeny-Rogachev** [comment]
I have the same problem and it often crash my app. Please fix this issue.

**Comment by tqlmorepassion** [comment]
+1

**Comment by tqlmorepassion** [comment]
I faced it because the RecyclerView not visible.
firstVisiblePosition=-1.

**Comment by repitch** [comment]
Same problem, waiting for the fix

**Comment by denzap** [comment]
This is annoying problem. Hope for quick fix

**Comment by ajh8894** [comment]
+1

**Comment by Vincent-Loi** [comment]
Same problem, but this workaround does the job for now 👍

> FlexboxLayoutManager use cachedViews which ViewHolder has been reseted. This my caused by RecyclerView is not visible
> 
> this is my workaround.
> 
> ```java
>         mListView.setItemViewCacheSize(10);
>         adapter.setHasStableIds(true);
> ```

**Comment by bmacedovoi** [comment]
Same issue. And the mentioned workaround didn't help me in my scenario.

**Comment by fxdong** [comment]
same problem + 1

**Comment by SergeyGorinov** [comment]
I've downloaded sources and changed some code for dealing with this issue. I've changed file FlexboxLayoutManager.java(line 1536):
`addView(view);` to `try { addView(view);  } catch (Exception e) {}`. And I've changed condition `if (position == 0) { return; }` to `if (position <= 0) { return; }` in file FlexboxItemDecoration.java (line 106). Know, it is not best solution, but seems it works without issues. Maybe this solution helps somebody.

**Comment by 2020gaurav** [comment]
Its being 4 years this issue is open, any plans to fix this?

**Comment by alexandre-thauvin** [comment]
Reproduced today.

**Comment by evjava** [comment]
Reproduced today.

**Comment by nambmt97s** [comment]
same problem when I have rotated the screen.
worked for me!
you just adapter.setHasStableIds(true) and override this method in your adapter.
override  fun getItemId(position: Int): Long {
        return position.toLong()
}

**Comment by jvlppm** [comment]
I'm using stableIds with getId returning a unique and constant id for each item, but I still received this exception

this is crashing my app and I can't even wrap it in an empty try-catch because the stack trace does not contain my code

```log
08-31 11:07:27.897 19274 19274 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
08-31 11:07:27.897 19274 19274 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:439)
08-31 11:07:27.897 19274 19274 E AndroidRuntime: 	at com.google.android.flexbox.FlexboxLayoutManager.updateLayoutState(FlexboxLayoutManager.java:2077)
08-31 11:07:27.897 19274 19274 E AndroidRuntime: 	at com.google.android.flexbox.FlexboxLayoutManager.handleScrollingMainOrientation(FlexboxLayoutManager.java:1993)
08-31 11:07:27.897 19274 19274 E AndroidRuntime: 	at com.google.android.flexbox.FlexboxLayoutManager.scrollVerticallyBy(FlexboxLayoutManager.java:1957)
08-31 11:07:27.897 19274 19274 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:1972)
08-31 11:07:27.897 19274 19274 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.scrollByInternal(RecyclerView.java:2071)
08-31 11:07:27.897 19274 19274 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3531)
08-31 11:07:27.897 19274 19274 E AndroidRuntime: 	at android.view.View.dispatchTouchEvent(View.java:14309)
08-31 11:07:27.897 19274 19274 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3112)
...
```

**Comment by pakkpl** [comment]
I have same issue, version 3.0.0

```
    java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
        at com.google.android.flexbox.FlexboxLayoutManager.updateLayoutState(FlexboxLayoutManager.java:2132)
        at com.google.android.flexbox.FlexboxLayoutManager.handleScrollingMainOrientation(FlexboxLayoutManager.java:1993)
        at com.google.android.flexbox.FlexboxLayoutManager.fixLayoutEndGap(FlexboxLayoutManager.java:845)
        at com.google.android.flexbox.FlexboxLayoutManager.onLayoutChildren(FlexboxLayoutManager.java:782)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3540)
```

**Comment by svitlanakrav** [comment]
+1

**Comment by GazeOne** [comment]
I have similar issue

java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
	at java.util.ArrayList.get(ArrayList.java:439)
	at com.google.android.flexbox.FlexboxLayoutManager.findLastReferenceChild(FlexboxLayoutManager.java:1211)
	at com.google.android.flexbox.FlexboxLayoutManager.computeScrollOffset(FlexboxLayoutManager.java:2251)
	at com.google.android.flexbox.FlexboxLayoutManager.computeVerticalScrollOffset(FlexboxLayoutManager.java:2238)
	at androidx.recyclerview.widget.RecyclerView.computeVerticalScrollOffset(RecyclerView.java:2206)
	at android.view.View.canScrollVertically(View.java:19156)

**Comment by frlgrd** [comment]
Same here

**Comment by pantasystem** [comment]
I have similar issue
```
Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 18, Size: 18
       at java.util.ArrayList.get(ArrayList.java:437)
       at com.google.android.flexbox.FlexboxLayoutManager.findFirstReferenceChild(FlexboxLayoutManager.java:29)
       at com.google.android.flexbox.FlexboxLayoutManager.updateAnchorFromChildren(FlexboxLayoutManager.java:446)
       at com.google.android.flexbox.FlexboxLayoutManager.updateAnchorInfoForLayout(FlexboxLayoutManager.java:446)
       at com.google.android.flexbox.FlexboxLayoutManager.onLayoutChildren(FlexboxLayoutManager.java:446)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:92)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:125)
       at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:8)
       at android.view.View.layout(View.java:23716)
       at android.view.ViewGroup.layout(ViewGroup.java:6413)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
       at android.view.View.layout(View.java:23716)
       at android.view.ViewGroup.layout(ViewGroup.java:6413)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:23716)
       at android.view.ViewGroup.layout(ViewGroup.java:6413)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:23716)
       at android.view.ViewGroup.layout(ViewGroup.java:6413)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:392)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:392)
       at com.google.android.material.bottomsheet.BottomSheetBehavior.onLayoutChild(BottomSheetBehavior.java:161)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:43)
       at android.view.View.layout(View.java:23716)
       at android.view.ViewGroup.layout(ViewGroup.java:6413)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:23716)
       at android.view.ViewGroup.layout(ViewGroup.java:6413)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:23716)
       at android.view.ViewGroup.layout(ViewGroup.java:6413)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:23716)
       at android.view.ViewGroup.layout(ViewGroup.java:6413)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:23716)
       at android.view.ViewGroup.layout(ViewGroup.java:6413)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
       at android.view.View.layout(View.java:23716)
       at android.view.ViewGroup.layout(ViewGroup.java:6413)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:799)
       at android.view.View.layout(View.java:23716)
       at android.view.ViewGroup.layout(ViewGroup.java:6413)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4097)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3438)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2350)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9194)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
       at android.view.Choreographer.doCallbacks(Choreographer.java:899)
       at android.view.Choreographer.doFrame(Choreographer.java:832)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7884)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by kpytb** [comment]
The same crash, v3.0.0
Please fix it
I have RecyclerView in RecyclerView, used FlexboxLayoutManager.
setHasStableIds with getItemId didn't help

Stacktrace:
Fatal Exception: java.lang.IndexOutOfBoundsException
Index: 2, Size: 1
java.util.ArrayList.get (ArrayList.java:437)
com.google.android.flexbox.FlexboxLayoutManager.findFirstReferenceChild (FlexboxLayoutManager.java:1199)
com.google.android.flexbox.FlexboxLayoutManager.updateAnchorFromChildren (FlexboxLayoutManager.java:1157)
com.google.android.flexbox.FlexboxLayoutManager.updateAnchorInfoForLayout (FlexboxLayoutManager.java:1052)
com.google.android.flexbox.FlexboxLayoutManager.onLayoutChildren (FlexboxLayoutManager.java:721)
androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2 (RecyclerView.java:4645)

android.view.ViewGroup.layout (ViewGroup.java:6505)
com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild (HeaderScrollingViewBehavior.java:149)
com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild (ViewOffsetBehavior.java:43)
com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild (AppBarLayout.java:2348)
androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout (CoordinatorLayout.java:953)

**Comment by hoanganhtuan95ptit** [comment]
I encountered the same issue as you. I rewrote the ***findFirstReferenceChild*** function and added a ***try-catch*** block to address it. I hope this helps!  

### Here is the modified class:  

[FlexboxLayoutManagerWrap](https://github.com/hoanganhtuan95ptit/Phonetics/blob/6858cc22e86fd5ee22aa5c0346fd704fbd85fb54/android/app/src/main/java/com/google/android/flexbox/FlexboxLayoutManagerWrap.java#L48)  

### Updated Code:
```java
private View findFirstReferenceChild(int itemCount) {
    assert mFlexboxHelper.mIndexToFlexLine != null;

    try {
        View firstFound = findReferenceChild(0, getChildCount(), itemCount);
        if (firstFound == null) {
            return null;
        }
        
        int firstFoundPosition = getPosition(firstFound);
        int firstFoundLinePosition = mFlexboxHelper.mIndexToFlexLine[firstFoundPosition];
        
        if (firstFoundLinePosition == NO_POSITION) {
            return null;
        }
        
        FlexLine firstFoundLine = mFlexLines.get(firstFoundLinePosition);
        return findFirstReferenceViewInLine(firstFound, firstFoundLine);
    } catch (Exception e) {
        if (onErrorListener != null) {
            onErrorListener.onError(e);
        }
        return null;
    }
}
