### ISSUE TITLE
FlexboxLayoutManager setLayoutManager use in FlexibleAdapter Error 

### ISSUE THREAD

**Issue by tcqq** [google/flexbox-layout#401]
Now my recyclerview used adapter is [FlexibleAdapter](https://github.com/davideas/FlexibleAdapter),  FlexibleAdapter support [use other LayoutManager](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Thirds-Layout-Managers), but flexbox-layout have  error. What did I do wrong? How should I change it?

# Error:
java.lang.ClassCastException: android.support.v7.widget.RecyclerView$LayoutParams cannot be cast to com.google.android.flexbox.FlexItem
                                                                   at com.google.android.flexbox.FlexboxHelper.calculateFlexLines(FlexboxHelper.java:438)
                                                                   at com.google.android.flexbox.FlexboxHelper.calculateVerticalFlexLines(FlexboxHelper.java:316)
                                                                   at com.google.android.flexbox.FlexboxLayoutManager.updateFlexLines(FlexboxLayoutManager.java:957)
                                                                   at com.google.android.flexbox.FlexboxLayoutManager.onLayoutChildren(FlexboxLayoutManager.java:716)
                                                                   at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
                                                                   at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3436)
                                                                   at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)

# Activity.java:
private void initRecyclerView() {
        mAdapter = new PublishChooseSkillsAdapter(getDatabaseList(), this);
        mAdapter.setNotifyMoveOfFilteredItems(true)
                .setAnimationOnForwardScrolling(true);
        mRecyclerView = findViewById(R.id.recycler_view);
        mRecyclerView.setAdapter(mAdapter);

        FlexibleFlexboxLayoutManager layoutManager = new FlexibleFlexboxLayoutManager(getContext());
        layoutManager.setFlexDirection(FlexDirection.COLUMN);
        layoutManager.setJustifyContent(JustifyContent.FLEX_END);
        mRecyclerView.setLayoutManager(layoutManager);

        mRecyclerView.setHasFixedSize(true); //Size of RV will not change
        mRecyclerView.setItemAnimator(new DefaultItemAnimator());

        // More settings
        mAdapter
                // Show Headers at startUp, 1st call, correctly executed, no warning log message!
                .setDisplayHeadersAtStartUp(true)
                .setStickyHeaders(true);
    }

# FlexibleFlexboxLayoutManager.java
public class FlexibleFlexboxLayoutManager extends FlexboxLayoutManager implements IFlexibleLayoutManager {

    public FlexibleFlexboxLayoutManager(Context context) {
        super(context);
    }

    public FlexibleFlexboxLayoutManager(Context context, int flexDirection) {
        super(context, flexDirection);
    }

    public FlexibleFlexboxLayoutManager(Context context, int flexDirection, int flexWrap) {
        super(context, flexDirection, flexWrap);
    }

    public FlexibleFlexboxLayoutManager(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {
        super(context, attrs, defStyleAttr, defStyleRes);
    }

    @Override
    public int getOrientation() {
        return OrientationHelper.VERTICAL;
    }

    @Override
    public int getSpanCount() {
        return 1;
    }
}

**Comment by thagikura** [comment]
It's a completely different library, sounds like you need to ask it to the maintainer of FlexibleAdapter.
