### ISSUE TITLE
Failed resolution of: Landroidx/core/view/ViewCompat

### ISSUE THREAD

**Issue by aneemtalukder** [google/flexbox-layout#463]
I've added FlexboxLayout to a layout xml file, and when I launch the Fragment that uses that layout file, I get the following:

```
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/view/ViewCompat;
        at com.google.android.flexbox.FlexboxLayout.onLayout(FlexboxLayout.java:565)
        at android.view.View.layout(View.java:19586)
        at android.view.ViewGroup.layout(ViewGroup.java:6053)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
        at android.view.View.layout(View.java:19586)
        at android.view.ViewGroup.layout(ViewGroup.java:6053)
        at android.support.v7.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:9322)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1615)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3336)
        at android.view.View.measure(View.java:21998)
        at android.support.constraint.ConstraintLayout.internalMeasureChildren(ConstraintLayout.java:1180)
        at android.support.constraint.ConstraintLayout.onMeasure(ConstraintLayout.java:1249)
        at android.view.View.measure(View.java:21998)
        at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1308)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.widget.ScrollView.onMeasure(ScrollView.java:350)
        at android.view.View.measure(View.java:21998)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:21998)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:21998)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:21998)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:21998)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:21998)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:21998)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:721)
        at android.view.View.measure(View.java:21998)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2410)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1498)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1751)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:789)
```

Any idea what is happening here?

**Comment by MGaetan89** [comment]
Are you using AndroidX or the Support Libraries in your project?
Flexbox 1.0.0 is meant to be used with the Support Libraries, Flexbox 1.1.0 is for AndroidX.

**Comment by aneemtalukder** [comment]
Thank you! This was indeed the issue! This should really be documented, I would have had no other way of knowing this information.

**Comment by MGaetan89** [comment]
It's true that it's not explicitly documented, but you can see this change in the [releases](https://github.com/google/flexbox-layout/releases) section.

@thagikura what do you think about a note to the Readme to mention that?

**Comment by MittapalliHareesh** [comment]
Thanks for the solution, due to there is no direct update at their github blog about versions everyone using 1.1.0 and facing this issue.

**Comment by thagikura** [comment]
Sorry about the confusion added the notice that starting from 1.1.0, the project needs to be migrated to AndroidX.

Thanks @MGaetan89 .

**Comment by ankurda28** [comment]
Getting same issue on some devices:
Device Name; Xiaomi
Android OS= 9

Using flexbox v1.1.0 with Androidx
