### ISSUE TITLE
The FlexbloxLayout tag is simply not working ?

### ISSUE THREAD

**Issue by Aryanr64x** [google/flexbox-layout#473]
- [x] I have searched [existing issues](https://github.com/google/flexbox-layout/issues) and confirmed this is not a duplicate

I install  the Flexbox layout and typed the following code in android studio 
```
    <com.google.android.flexbox.FlexboxLayout
      xmlns:android="http://schemas.android.com/apk/res/android"
      xmlns:app="http://schemas.android.com/apk/res-auto"
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      app:flexWrap="wrap"
      app:alignItems="stretch"
      app:alignContent="stretch" >

    <TextView
        android:id="@+id/textview1"
        android:layout_width="120dp"
        android:layout_height="80dp"
        app:layout_flexBasisPercent="50%"
        />

    <TextView
        android:id="@+id/textview2"
        android:layout_width="80dp"
        android:layout_height="80dp"
        app:layout_alignSelf="center"
        />

    <TextView
        android:id="@+id/textview3"
        android:layout_width="160dp"
        android:layout_height="80dp"
        app:layout_alignSelf="flex_end"
        />
    </com.google.android.flexbox.FlexboxLayout>

```

But the previwer is unable to display any thing on the screen . When I ran the app even then noting appeared on the phone (just like the previer).
The previwer does gives an error though

`java.lang.NoClassDefFoundError: android/view/View$OnUnhandledKeyEventListener
	at com.google.android.flexbox.FlexboxLayout.onLayout_Original(FlexboxLayout.java:564)
	at com.google.android.flexbox.FlexboxLayout.onLayout(FlexboxLayout.java)
	at android.view.View.layout_Original(View.java:19659)
	at android.view.View_Delegate.layout(View_Delegate.java:91)
	at android.view.View.layout(View.java:19645)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout_Original(View.java:19659)
	at android.view.View_Delegate.layout(View_Delegate.java:91)
	at android.view.View.layout(View.java:19645)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
	at android.view.View.layout_Original(View.java:19659)
	at android.view.View_Delegate.layout(View_Delegate.java:91)
	at android.view.View.layout(View.java:19645)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:346)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:384)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:193)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:544)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$3(RenderTask.java:678)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: android.view.View$OnUnhandledKeyEventListener
	at org.jetbrains.android.uipreview.ModuleClassLoader.load(ModuleClassLoader.java:180)
	at com.android.tools.idea.rendering.RenderClassLoader.findClass(RenderClassLoader.java:61)
	at org.jetbrains.android.uipreview.ModuleClassLoader.findClass(ModuleClassLoader.java:118)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.jetbrains.android.uipreview.ModuleClassLoader.loadClass(ModuleClassLoader.java:213)
	... 26 more
`

I am also using the right version of the library

## Version of the flexbox library
flexbox:1.0.0

**Comment by vsd-codesode** [comment]
I could confirm that issue is valid in flexbox version 1.1.0.
How could we be certain that it is issue with flex library or IDE itself?

**Comment by Aryanr64x** [comment]
@vsd-codesode This is because because when I launch the app in my android device it still does not shows anything there. Hence its not only an IDE problem

**Comment by thagikura** [comment]
Hi, 

Thanks for the report.

The issue that nothing appeared is highly likely an issue with the Android Studio. 
If so, could you report the issue to the Android Studio issue tracker?

If the issue that nothing appeared on the phone is reproducible, it's an issue with the flexbox-layout library. But I couldn't reproduce it on my phone.
Is the issue that nothing appeared on your phone still reproducible?

**Comment by Aryanr64x** [comment]
I ended up migrating to android x. It works there (version 1.1.0) . The error was in version 1.0.0 (Without android x).

**Comment by SmileHub** [comment]
Updated android studio tu 3.3,
Migrated to android x, successfully compiled the project and launched and tested it.
Then decided to try Flexbox and added dependency:
`implementation 'com.google.android:flexbox:1.1.0'`

pasted in new fragment`s xml
```
<com.google.android.flexbox.FlexboxLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    app:flexWrap="wrap"
    app:alignItems="stretch"
    app:alignContent="stretch"
    android:layout_width="180dp"
    android:layout_height="60dp">


    <TextView
        android:id="@+id/textview1"
        android:layout_width="120dp"
        android:layout_height="80dp"
        app:layout_flexBasisPercent="50%"
        />

    <TextView
        android:id="@+id/textview2"
        android:layout_width="80dp"
        android:layout_height="80dp"
        app:layout_alignSelf="center"
        />

    <TextView
        android:id="@+id/textview3"
        android:layout_width="160dp"
        android:layout_height="80dp"
        app:layout_alignSelf="flex_end"
        />

</com.google.android.flexbox.FlexboxLayout>
```

and design in UI doesn't get rendered, receiving an error:
```
java.lang.ClassNotFoundException: com.google.android.flexbox.R$styleable
	at org.jetbrains.android.uipreview.ModuleClassLoader.load(ModuleClassLoader.java:190)
	at com.android.tools.idea.rendering.RenderClassLoader.findClass(RenderClassLoader.java:61)
	at org.jetbrains.android.uipreview.ModuleClassLoader.findClass(ModuleClassLoader.java:124)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.jetbrains.android.uipreview.ModuleClassLoader.loadClass(ModuleClassLoader.java:224)
	at com.google.android.flexbox.FlexboxLayout.<init>(FlexboxLayout.java:219)
	at com.google.android.flexbox.FlexboxLayout.<init>(FlexboxLayout.java:213)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:403)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:186)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:144)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:299)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:418)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:429)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:333)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:394)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:325)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:385)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:193)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:509)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$4(RenderTask.java:638)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by Ozaoujal** [comment]
> com.google.android:flexbox

after long time of searching, this worked for me, thank you @SmileHub

**Comment by Ozaoujal** [comment]
> Updated android studio tu 3.3, Migrated to android x, successfully compiled the project and launched and tested it. Then decided to try Flexbox and added dependency: `implementation 'com.google.android:flexbox:1.1.0'`
> 
> pasted in new fragment`s xml and it seems all worked out.

After many hours stucking in this issue, this one worked for me!
