### ISSUE TITLE
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException length=10; index=-1

### ISSUE THREAD

**Issue by faldujaldeep** [google/flexbox-layout#586]
Does anyone know how to fix this issue? This is the crash report from the firebase and not able to find the root cause and even not able to reproduce.

SDK  : implementation 'com.google.android:flexbox:2.0.1'

Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
       at com.google.android.flexbox.FlexboxLayoutManager.updateLayoutState(FlexboxLayoutManager.java:2051)
       at com.google.android.flexbox.FlexboxLayoutManager.handleScrollingMainOrientation(FlexboxLayoutManager.java:1971)
       at com.google.android.flexbox.FlexboxLayoutManager.scrollVerticallyBy(FlexboxLayoutManager.java:1935)
       at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:1972)
       at androidx.recyclerview.widget.RecyclerView.scrollByInternal(RecyclerView.java:2071)
       at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3531)
       at android.view.View.dispatchTouchEvent(View.java:11797)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2964)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2643)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:451)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1829)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3375)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:413)
       at android.view.View.dispatchPointerEvent(View.java:12038)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4884)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4695)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4231)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4284)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4250)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4377)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4258)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4434)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4231)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4284)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4250)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4258)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4231)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6793)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6765)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6726)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6901)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:254)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:214)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6869)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6924)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1029)
       at android.view.Choreographer.doCallbacks(Choreographer.java:841)
       at android.view.Choreographer.doFrame(Choreographer.java:766)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1015)
       at android.os.Handler.handleCallback(Handler.java:794)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:6651)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)

**Comment by Uncreated** [comment]
I have same problem. I can't reproduce this crash.

**Comment by angeleskilija** [comment]
+1

**Comment by IdioticMadman** [comment]
+1

**Comment by MrRightDongYuJie1314** [comment]
+1

**Comment by kslakhani** [comment]
So where is the solution.
I had a workaround.
Just add slight delay milis like 2000 before you add view or set the visibility
